"use client";

import { useState } from "react";
import { PatientShell } from "@/components/patient/patient-shell";
import { renderPlanComponent } from "./cards";
import { HaloAiFab } from "./halo-ai-fab";
import { CARE_TEAMS, type CareTeam } from "@/lib/care-teams-seed";

export function PatientCarePlanScreen({
  firstName,
  teams = CARE_TEAMS,
}: {
  firstName: string;
  teams?: CareTeam[];
}) {
  const [activeId, setActiveId] = useState(teams[0]?.id ?? "");
  const active = teams.find((t) => t.id === activeId) ?? teams[0];

  return (
    <>
    <PatientShell
      greeting={`Your plan, ${firstName}.`}
      subhead="Generated by your care teams. Tap a team to switch."
    >
      <div className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1">
        {teams.map((team) => {
          const isActive = team.id === active?.id;
          const ringClass = isActive
            ? "bg-[color:var(--halo-green)] text-white"
            : "bg-white text-[color:var(--halo-ink)] hover:bg-[color:var(--halo-green-soft)]/40";
          return (
            <button
              key={team.id}
              type="button"
              onClick={() => setActiveId(team.id)}
              className={`flex-none rounded-2xl border border-[color:var(--halo-ink)]/10 px-4 py-2 text-left transition ${ringClass}`}
            >
              <div className="text-[11px] font-medium uppercase tracking-wider opacity-80">
                {team.lead}
              </div>
              <div className="text-sm font-semibold">{team.name}</div>
              <div className="mt-0.5 text-[11px] opacity-80">{team.specialty}</div>
            </button>
          );
        })}
      </div>

      {active && (
        <>
          {active.items.map((item) => (
            <div key={item.id}>{renderPlanComponent(item)}</div>
          ))}
        </>
      )}
    </PatientShell>
    <HaloAiFab />
    </>
  );
}
